defaults: &defaults
  docker:
  - image: golang:1.11
  working_directory: /go/src/github.com/kubermatic/cluster-api-provider-digitalocean

version: 2
jobs:
  checkout_code:
    <<: *defaults
    steps:
    - checkout
    - save_cache:
        key: repo-{{ .Environment.CIRCLE_SHA1 }}
        paths:
        - /go/src/github.com/kubermatic/cluster-api-provider-digitalocean

  check-dependencies:
    <<: *defaults
    steps:
    - restore_cache:
        key: repo-{{ .Environment.CIRCLE_SHA1 }}
    - run: export DEP_RELEASE_TAG=v0.5.0; curl https://raw.githubusercontent.com/golang/dep/master/install.sh | sh
    - run: dep status

  lint:
    <<: *defaults
    docker:
    - image: quay.io/kubermatic/gometalinter:latest
    steps:
    - restore_cache:
        key: repo-{{ .Environment.CIRCLE_SHA1 }}
    - run: gometalinter --config gometalinter.json ./...

  test:
    <<: *defaults
    steps:
    - restore_cache:
        key: repo-{{ .Environment.CIRCLE_SHA1 }}
    - run: go test -race ./...

  build:
    <<: *defaults
    steps:
    - restore_cache:
        key: repo-{{ .Environment.CIRCLE_SHA1 }}
    - run: DEP_RELEASE_TAG=v0.5.0 curl https://raw.githubusercontent.com/golang/dep/master/install.sh | sh
    - run: make compile
    - save_cache:
        key: cluster-api-provider-digitalocean-{{ .Revision }}
        paths:
        - /go/src/github.com/kubermatic/cluster-api-provider-digitalocean

  publish:
    <<: *defaults
    docker:
    - image: docker:stable
    steps:
    - restore_cache:
        key: repo-{{ .Environment.CIRCLE_SHA1 }}
    - restore_cache:
        key: cluster-api-provider-digitalocean-{{ .Revision }}
    - setup_remote_docker
    - run: apk update && apk add make bash git
    - run: |
        set -e
        export GIT_TAG=$CIRCLE_TAG
        docker login -u "${DOCKERHUB_USER}" -p "${DOCKERHUB_PASS}" quay.io
        make images-nodep
        make push-nodep

  e2e:
    machine: true
    environment:
      CHANGE_MINIKUBE_NONE_USER: true
      KUBERNETES_VERSION: v1.10.0
    steps:
    - run:
        name: Create directory structure
        command: |
          # Create directory
          sudo mkdir -p /go/src/github.com/kubermatic/cluster-api-provider-digitalocean
          # Set up permissions
          sudo chown -R $USER:$USER /go
    - restore_cache:
        key: repo-{{ .Environment.CIRCLE_SHA1 }}
    - run:
        name: Install dependencies
        command: |
          # Download kubectl, which is a requirement for using minikube and running e2e tests.
          curl -Lo kubectl https://storage.googleapis.com/kubernetes-release/release/${KUBERNETES_VERSION}/bin/linux/amd64/kubectl && chmod +x kubectl && sudo mv kubectl /usr/local/bin/
          # Download minikube.
          curl -Lo minikube https://storage.googleapis.com/minikube/releases/latest/minikube-linux-amd64 && chmod +x minikube && sudo mv minikube /usr/local/bin/
          # Download kubeadm.
          curl -Lo kubeadm https://storage.googleapis.com/kubernetes-release/release/${KUBERNETES_VERSION}/bin/linux/amd64/kubeadm && chmod +x kubeadm && sudo mv kubeadm /usr/bin/
    - run:
        name: Set up minikube
        command: |
          # Make root rshared in order to fix kube-dns problems.
          sudo mount --make-rshared /
          # Start minikube.
          sudo minikube start --vm-driver=none --bootstrapper=localkube --kubernetes-version=${KUBERNETES_VERSION} --feature-gates=CustomResourceSubresources=true --extra-config=apiserver.Authorization.Mode=RBAC
          # Set correct permissions on minikube and kubeconfig files.
          sudo chown -R $USER:$USER $HOME/.kube
          sudo chown -R $USER:$USER $HOME/.minikube
          # Update the kubeconfig to use the minikube cluster.
          minikube update-context
          # Copy kubeconfig file to /etc/kubernetes.
          sudo mkdir -p /etc/kubernetes
          sudo cp $HOME/.kube/config /etc/kubernetes/admin.conf
          sudo chown $USER:$USER /etc/kubernetes/admin.conf
    - run:
        name: Wait for cluster to become ready
        command: |
          # Wait for Kubernetes to be up and ready.
          JSONPATH='{range .items[*]}{@.metadata.name}:{range @.status.conditions[*]}{@.type}={@.status};{end}{end}'; until kubectl get nodes -o jsonpath="$JSONPATH" 2>&1 | grep -q "Ready=True"; do sleep 1; echo "waiting for node to become ready"; kubectl get nodes; done
          # Ensure default ServiceAccount is a cluster-admin, as a workaround required for kube-dns when running with RBAC enabled.
          kubectl create clusterrolebinding add-on-cluster-admin --clusterrole=cluster-admin --serviceaccount=kube-system:default
          # Wait for kube-dns to become ready.
          JSONPATH='{range .items[*]}{@.metadata.name}:{range @.status.conditions[*]}{@.type}={@.status};{end}{end}'; until kubectl -n kube-system get pods -lk8s-app=kube-dns -o jsonpath="$JSONPATH" 2>&1 | grep -q "Ready=True"; do sleep 1;echo "waiting for kube-dns to be available"; kubectl get pods --all-namespaces; done
    - run:
        name: Generate manifests
        working_directory: /go/src/github.com/kubermatic/cluster-api-provider-digitalocean/clusterctl/examples/digitalocean
        command: ./generate-yaml.sh
    - run:
        name: Run clusterctl
        working_directory: /go/src/github.com/kubermatic/cluster-api-provider-digitalocean/clusterctl
        environment:
          GOPATH: /go
        command: |
          NODENAME=$(kubectl get nodes -o jsonpath="{range .items[*]}{@.metadata.name}{end}")
          kubectl label node ${NODENAME} node-role.kubernetes.io/master=
          # Disable clusterctl for now.
          #go run main.go create cluster --provider digitalocean -c examples/digitalocean/out/cluster.yaml -m examples/digitalocean/out/machines.yaml -p examples/digitalocean/out/provider-components.yaml -a examples/digitalocean/out/addons.yaml --existing-bootstrap-cluster-kubeconfig /etc/kubernetes/admin.conf

workflows:
  version: 2
  build:
    jobs:
    - checkout_code:
        filters:
          tags:
            only: /v.*/
    - check-dependencies:
        requires:
        - checkout_code
        filters:
          tags:
            only: /v.*/
    - lint:
        requires:
        - checkout_code
        filters:
          tags:
            only: /v.*/
    - test:
        requires:
        - checkout_code
        filters:
          tags:
            only: /v.*/
    - build:
        requires:
        - checkout_code
        filters:
          tags:
            only: /v.*/
    - publish:
        requires:
        - build
        - test
        - check-dependencies
        filters:
          branches:
            ignore: /.*/
          tags:
            only: /v.*/
    - e2e:
        requires:
        - checkout_code
        filters:
          tags:
            only: /v.*/

